version: '2'

services:
  sensor:
    build: ./sensor/sensor
    privileged: true
    ports:
      - "8000:8000"
    environment:
      DEVICE_DB_LOCATION: $DEVICE_DB_LOCATION
      PROMETHEUS_JOB_NAME: $PROMETHEUS_JOB_NAME
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'

  prometheus:
    build: ./prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=15d'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
    environment:
      GRAFANA_CLOUD_PUSH_URL: ${GRAFANA_CLOUD_PUSH_URL}
      GRAFANA_CLOUD_USERNAME: ${GRAFANA_CLOUD_USERNAME}
      GRAFANA_CLOUD_PASSWORD: ${GRAFANA_CLOUD_PASSWORD}
      DEVICE_DB_LOCATION: ${DEVICE_DB_LOCATION}
      PROMETHEUS_JOB_NAME: ${PROMETHEUS_JOB_NAME}

volumes:
  prometheus-data:
