version: '2.1'

volumes:
  influx_data: {}
  grafana_data: {}

services:
  sensor:
    build: ./sensor/sensor
    restart: unless-stopped
    privileged: true
    depends_on:
      - influxdb
    environment:
      - INFLUX_DB_BUCKET
      - INFLUX_DB_TOKEN
      - INFLUX_DB_ORG
      - DEVICE_DB_LOCATION
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'

  influxdb:
    restart: unless-stopped
    image: influxdb:2.7-alpine
    volumes:
      - influx_data:/var/lib/influxdb2
      - influx_data:/etc/influxdb2
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD
      - DOCKER_INFLUXDB_INIT_ORG
      - DOCKER_INFLUXDB_INIT_BUCKET
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN

  grafana:
    build: ./sensor/grafana
    restart: unless-stopped
    depends_on:
      - influxdb
    ports:
      - "80:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel
      - GF_SECURITY_ADMIN_PASSWORD
      - GF_SERVER_ROOT_URL=http://localhost
    labels:
      io.balena.features.supervisor-api: '1'

  telegraf:
    image: telegraf:1.28-alpine
    restart: unless-stopped
    depends_on:
      - influxdb
    environment:
      - INFLUX_DB_BUCKET
      - INFLUX_DB_TOKEN
      - INFLUX_DB_ORG
      - HOST_PROC=/rootfs/proc
      - HOST_SYS=/rootfs/sys
      - HOST_ETC=/rootfs/etc
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
    labels:
      io.balena.features.procfs: '1'
      io.balena.features.sysfs: '1'
