version: '3.8'

services:  
  # Sensor service - sends metrics to Grafana Cloud
  sensor:
    build: ./sensor
    restart: unless-stopped
    # Access to the Raspberry Pi system. I2C for sensor communication, GPIO for shutdown buttons
    privileged: true
    env_file: ../.env  # Environment file in root folder
    networks:
      priv_lan:
        ipv4_address: 192.168.1.192

networks:
  # The priv_lan network is already setup, so it is an 'external' network
  priv_lan:
    external:
      name: priv_lan

